/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wo_yinyuetai_utils_S2K */

#ifndef _Included_wo_yinyuetai_utils_S2K
#define _Included_wo_yinyuetai_utils_S2K
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wo_yinyuetai_utils_S2K
 * Method:    s2k
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wo_yinyuetai_utils_S2K_s2k
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
